{{- if .Values.cassandraReaper.enableReaper }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-reaper
  namespace: {{ .Release.Namespace }}
  labels:
    app: cassandra-reaper
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.cassandraReaper.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cassandra-reaper
    spec:
      nodeSelector:
        {{- range $key, $val := .Values.cassandraReaper.nodeSelector }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
      initContainers:
      - name: cassandra-reaper-bootstrap
        image: "quay.io/mysocialapp/docker-backup-common:{{ .Values.cassandraBackup.backupImageVersion }}"
        args:
          - /bin/bash
          - -c
          - kubectl -n {{ .Release.Namespace }} exec cassandra-0 /usr/local/apache-cassandra/scripts/reaper_ks_bootstrap.sh
        volumeMounts:
        - name: {{ template "kubernetes.name" . }}
          mountPath: /usr/local/apache-cassandra/scripts
      volumes:
        - name: {{ template "kubernetes.name" . }}
          configMap:
            name: {{ template "kubernetes.name" . }}
            defaultMode: 0775
      containers:
      - name: cassandra-reaper
        image: "thelastpickle/cassandra-reaper:{{ .Values.cassandraReaper.imageVersion }}"
        env:
          - name: REAPER_JMX_AUTH_USERNAME
            value: "{{ .Values.cassandraReaper.jmxAuth.username }}"
          - name: REAPER_JMX_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cassandra-reaper
                key: REAPER_JMX_AUTH_PASSWORD
          - name: REAPER_STORAGE_TYPE
            value: "cassandra"
          - name: REAPER_CASS_CLUSTER_NAME
            value: "{{ default .Release.Namespace .Values.cassandraReaper.clusterName }}"
          - name: REAPER_CASS_CONTACT_POINTS
            value: "[{{ .Values.cassandraReaper.contactPoints }}]"
          {{- range $key, $val := .Values.cassandraReaper.envVariables }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
        ports:
        - name: admin
          containerPort: {{ .Values.cassandraReaper.envVariables.REAPER_SERVER_ADMIN_PORT }}
        - name: app
          containerPort: {{ .Values.cassandraReaper.envVariables.REAPER_SERVER_APP_PORT }}
        - name: jmx
          containerPort: 7199
        livenessProbe:
          tcpSocket:
            port: {{ .Values.cassandraReaper.envVariables.REAPER_SERVER_APP_PORT }}
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.cassandraReaper.envVariables.REAPER_SERVER_ADMIN_PORT }}
          initialDelaySeconds: 180
          timeoutSeconds: 10
        resources:
{{ toYaml .Values.cassandraReaper.resources | indent 10 }}
{{- end }}
