{{- if .Values.casspoke.enablePoke }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: casspoke-{{ .Release.Namespace }}
  namespace: observability
  labels:
    app: casspoke
    prometheus: observability
spec:
  selector:
    matchLabels:
      app: casspoke
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 59s
{{- end }}